//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerWPFApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseComputerEntities : DbContext
    {
        public DatabaseComputerEntities()
            : base("name=DatabaseComputerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Видеокарта> Видеокарта { get; set; }
        public virtual DbSet<Производители> Производители { get; set; }
        public virtual DbSet<Процессор> Процессор { get; set; }
        public virtual DbSet<Компьютер> Компьютер { get; set; }
    }
}
