//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerWPFApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Компьютер
    {
        public int Код { get; set; }
        public Nullable<int> КодПроизводителя { get; set; }
        public Nullable<int> КодПроцессора { get; set; }
        public Nullable<int> КодВидеокарты { get; set; }
        public string МатеринскаяПлата { get; set; }
        public string ТипОперативнойПамяти { get; set; }
        public Nullable<int> ОбъемОперативнойПамяти { get; set; }
        public string ТипНакопителяДанных { get; set; }
        public Nullable<int> ОбъемНакопителя { get; set; }
        public byte[] Изображение { get; set; }
    
        public virtual Видеокарта Видеокарта { get; set; }
        public virtual Производители Производители { get; set; }
        public virtual Процессор Процессор { get; set; }
    }
}
