//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerWPFApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Процессор
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Процессор()
        {
            this.Компьютер = new HashSet<Компьютер>();
        }
    
        public int Код { get; set; }
        public string Модель { get; set; }
        public Nullable<int> КолвоЯдер { get; set; }
        public Nullable<double> Частота { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Компьютер> Компьютер { get; set; }
    }
}
